### ISSUE TITLE
Width for dropdown list and description labels

### ISSUE THREAD

**Issue by gradzie** [jasongrout/ipythonwidgets#2]
Hello,
I have been struggling for days on trying to find out a way to:
1. adjusting the width of the dropdown list to the content of the list (long strings in my case);
2. increasing the width of the description label (for RadioButtons) in order to see the label on one single line only.

I would be very grateful to receive your help.
Warm regards,
Graziella

**Comment by jasongrout** [comment]
Thanks. I've moved this issue to the pywidgets repo: https://github.com/jupyter-widgets/ipywidgets/issues/2050

(This repo is for a couple of specific widgets I worked on years ago; the ipywidgets repo is the main widgets repo)
